#pragma once

#define GLIB_FAIL_INIT_GLFW 0x10

#define GLIB_FAIL_FILE_READ 0x20

#define GLIB_FAIL_SHADER_LINK 0x30
#define GLIB_FAIL_SHADER_COMPILEv 0x31
#define GLIB_FAIL_SHADER_COMPILEf 0x32

#define GLIB_FRAMEBUFFER_UNKNOWN_TYPE 0x40
#define GLIB_FRAMEBUFFER_NOT_COMPLETE 0x41

#define GLIB_SOUND_FILE_READ_FAIL 0x50
#define GLIB_SOUND_UNSUPPORTED_FORMAT 0x51
#define GLIB_SOUND_FILE_OPEN_FAIL 0x52
#define GLIB_SOUND_INTERNAL_ERROR 0x53